# Generated by Django 5.1.4 on 2025-01-06 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApplication', '0003_blogapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogapp',
            old_name='itle',
            new_name='title',
        ),
    ]
