# Generated by Django 5.1.5 on 2025-01-23 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApplication', '0007_alter_blogapp_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogapp',
            options={},
        ),
        migrations.RemoveField(
            model_name='blogapp',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='blogapp',
            name='updated_date',
        ),
    ]
